version: '3.7'

services:
  airflow-prod:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - AIRFLOW_ENV=PRODUCITON
    volumes:
      - ./airflow:/root/airflow
    networks:
      web:
        aliases:
          - com_profcomff_airflow

volumes:
  airflow-libs-prod:

networks:
  web:
    external: true
    name: web
