version: '3.8'

services:
  airflow:
    image: ghcr.io/profcomff/dwh-airflow:test
    depends_on:
      - postgres
    pull_policy: always
    ports:
      - 8080:8080
    restart: on-failure:5
    environment:
      - AIRFLOW_ENV=DEV
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres@postgres:5432/postgres
    volumes:
      - ./pipelines:/airflow/dags/dwh-pipelines
      - ./start_local.sh:/start_inc.sh

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
