version: '3.7'

services:
  airflow-prod:
    build: .
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - AIRFLOW_ENV=PRODUCITON
    volumes:
      - ./start_local:/start_inc.sh
